version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: framework
    restart: always
    working_dir: /framework
    volumes:
      - ../:/framework
  nginx:
    image: nginx:1.23.4-alpine
    container_name: framework-nginx
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - ../:/framework
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: framework-db
    image: mysql:8.0.32
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
